# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

dist: bin

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/thomaslaurenson/narc/cmd.Version={{.Version}}

archives:
  - formats: [binary]

checksum:
  name_template: checksums.txt
  algorithm: sha256

signs:
  - artifacts: checksum
    cmd: cosign
    args:
      - sign-blob
      - --yes
      - --output-signature=${signature}
      - ${artifact}
    signature: ${artifact}.sig
