# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: narc

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/thomaslaurenson/narc/cmd.Version={{.Version}}

archives:
  - formats: [binary]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt
  algorithm: sha256

signs:
  - artifacts: checksum
    cmd: cosign
    signature: ${artifact}.sig
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"

release:
  prerelease: true
  draft: false
  name_template: "Dev (Pre-release)"

changelog:
  disable: true

git:
  ignore_tags:
    - "*-dev"
