binary: narc

platforms:
  linux_amd64:  ./dist/narc-linux-amd64
  linux_arm64:  ./dist/narc-linux-arm64
  darwin_amd64: ./dist/narc-darwin-amd64
  darwin_arm64: ./dist/narc-darwin-arm64
  windows_amd64: ./dist/narc-windows-amd64.exe
