---
name: Lint

on: workflow_call

permissions:
  contents: read

jobs:
  go_lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.11.4

      - name: Check formatting
        run: make fmt_check

      - name: Check go mod tidy
        run: make mod_check

      - name: Run golangci-lint
        run: make lint
