name: Main

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
      - "cmd/**"
      - "internal/**"
      - "main.go"
      - "go.mod"
      - "go.sum"
      - "Makefile"

concurrency:
  group: prerelease
  cancel-in-progress: true

permissions:
  contents: write

jobs:

  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  prerelease:
    needs: [lint, test]
    uses: ./.github/workflows/prerelease.yml
    secrets: inherit
