---
name: Prerelease

on: workflow_call

permissions:
  contents: write

jobs:
  prerelease:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - uses: sigstore/cosign-installer@v4.1.2

      - name: Set dev tag
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -f dev
          git push origin dev --force

      - name: Delete existing dev release (using gh)
        run: |
          gh release delete dev --yes \
          --cleanup-tag 2>/dev/null \
          || echo "No existing dev release to delete"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Recreate dev tag (cleanup-tag removed it)
        run: |
          git tag -f dev
          git push origin dev --force

      - uses: goreleaser/goreleaser-action@v7
        with:
          version: "~> v2"
          args: release --clean --config .goreleaser.prerelease.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
