name: Tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:

  lint:
    uses: ./.github/workflows/lint.yml

  release:
    needs: lint
    uses: ./.github/workflows/release.yml
    secrets: inherit
